import { Avatar, Center, Divider, Tag, TagLabel } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Center h="50px">
          <Link href="/about">About</Link>
        </Center>
      </nav>

      <Center h="50px">
        <Divider />
      </Center>

      <main>
        <Center h="50px">
          <h1>Welcome to the Home page</h1>
        </Center>
      </main>

      <Center h="50px">
        <Divider />
      </Center>

      <footer>
        <Center h="50px">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </Center>
      </footer>
    </div>
  );
};

export default Home;
